config/routes.rb
Rails.application.routes.draw do
  resources :contacts

  devise_for :users

  root 'contacts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  validates :firstName, presence: true
  validates :lastName, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [ :show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    if signed_in?
      @contacts = current_user.contacts.all.paginate :page => params[:page], :per_page => 10
    else
      redirect_to "/users/sign_in"
    end
    #@contacts = Contact.all.limit(10)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show

    @contact = Contact.find params[:id]
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit

  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.create(contact_params)
    @contact[:user_id] = current_user[:id]



    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

    def signed_in?
      !current_user.nil?
    end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params[:contact].permit(:firstName, :lastName, :middleName, :email, :phoneNumber)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= form_for @contact, :url => { :action => "update" }  do |c|  %>
    <table class="table">
      <tr>
        <td>First Name:</td>
        <td>
          <%= c.text_field  :firstName %>
          <span class="help-inline"><%= @contact.errors[:firstName].join(", ")%></span>
        </td>
      </tr>
      <tr>
        <td>Middle Name:</td>
        <td>
          <%= c.text_field  :middleName %>
          <span class="help-inline"><%= @contact.errors[:middleName].join(", ")%></span>
        </td>
      </tr>
      <tr>
        <td>Last Name:</td>
        <td>
          <%= c.text_field  :lastName %>
          <span class="help-inline"><%= @contact.errors[:lastName].join(", ")%></span>
        </td>
      </tr>
      <tr>
        <td>Email:</td>
        <td>
          <%= c.email_field  :email %>
          <span class="help-inline"><%= @contact.errors[:email].join(", ")%></span>
        </td>
      </tr>
      <tr>
        <td>Phone Number:</td>
        <td>
          <%= c.text_field  :phoneNumber %>
          <span class="help-inline"><%= @contact.errors[:phoneNumber].join(", ")%></span>

        </td>
      </tr>
    </table>
    <%= c.submit "Save Changes", class: "btn btn-primary" %>
<%end%>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Owner ID</th>
      <th>First Name</th>
      <th>Middle Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Phone Number</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td>  <%= contact.user_id %><br /></td>
        <td>  <%= contact.firstName %><br /></td>
        <td>  <%= contact.middleName %><br /></td>
        <td>  <%= contact.lastName %><br /></td>
        <td>  <%= contact.email %><br /></td>
        <td>  <%= contact.phoneNumber %><br /></td>

        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination">
  <%= will_paginate @contacts, renderer: BootstrapPagination::Rails %>
</div>

<br>

<%= link_to 'New Contact', new_contact_path, class: "btn btn-primary"  %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= form_for @contact, :url => { :action => "create" }  do |c|  %>

    <table class="table">
      <tr>
        <td>First Name:</td>
        <td>
          <%= c.text_field  :firstName %>
          <span class="help-inline"><%= @contact.errors[:firstName].join(", ")%></span>
        </td>
      </tr>
      <tr>
        <td>Middle Name:</td>
        <td>
            <%= c.text_field  :middleName %>
            <span class="help-inline"><%= @contact.errors[:middleName].join(", ")%></span>
        </td>
      </tr>
      <tr>
        <td>Last Name:</td>
        <td>
          <%= c.text_field  :lastName %>
          <span class="help-inline"><%= @contact.errors[:lastName].join(", ")%></span>
        </td>
      </tr>
      <tr>
        <td>Email:</td>
        <td>
          <%= c.email_field  :email %>
          <span class="help-inline"><%= @contact.errors[:email].join(", ")%></span>
        </td>
      </tr>
      <tr>
        <td>Phone Number:</td>
        <td>
          <%= c.text_field  :phoneNumber %>
          <span class="help-inline"><%= @contact.errors[:phoneNumber].join(", ")%></span>

        </td>
      </tr>
    </table>
    <%= c.submit "Add Contact", class: "btn btn-primary" %>
<%end%>


<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<h1>Contact: <%= @contact[:id]%></h1>


<table class="table">
  <tr>
    <td>First Name:</td>
    <td>
      <%= @contact[:firstName]%>
    </td>
  </tr>
  <tr>
    <td>Middle Name:</td>
    <td>
      <%= @contact[:middleName]%>
    </td>
  </tr>
  <tr>
    <td>Last Name:</td>
    <td>
      <%= @contact[:lastName]%>
    </td>
  </tr>
  <tr>
    <td>Email:</td>
    <td>
      <%= @contact[:email]%>
    </td>
  </tr>
  <tr>
    <td>Phone Number:</td>
    <td>
      <%= @contact[:phoneNumber]%>
    </td>
  </tr>
</table>

<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Contacts-RubyOnRails" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Contacts- RubyOnRails</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">

          <ul class="nav navbar-nav navbar-right">
            <% !if signed_in? %>
                <li><%= link_to current_user.email, "/users/sign_in"  %></li>
                <li><%= link_to "Sign Out", "/users/sign_out", :method => :delete%></li>

            <% else %>
                <li><%= link_to "Sign In", "/users/sign_in"  %></li>
                <li><%= link_to "Register", "/users/sign_up"  %></li>
            <% end %>

          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; Daniel Mashuda 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>